name: Check PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest

    # Run the job only for specific branches
    if: startsWith(github.base_ref, 'rc_') || endsWith(github.base_ref, '.x') || github.base_ref == 'develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Description
        run: python .github/scripts/pr_description_check.py
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ secrets.MH_PUSH }}